name: Merge
on: pull_request
jobs:
  on-create:
    steps:
      - name: "Checkout repository"
        uses: actions/checkut@v3
      - name: "Move into repo"
        run: "ls"
      - name: "Print event"
        runs: echo '${{ github }}'
