name: Merge
on: pull_request
jobs:
  on-create:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Print event"
        run: echo '${{ github }}'
