name: Merge
on:
  pull_request:
    types: [closed]
jobs:
  on-create:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Fix migrations"
        uses: bluewave41/migration-action@main
        with:
          path: server
      - name: Upload log file (even if previous step fails)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: log.json
